version: 1
groups:
  - annotation: ckanext-language-domains settings
    options:
      - key: ckanext.language_domains.domain_map
        example: {"en": ["example.com"], "fr": ["exemple.com"]}
        description: |
          Dictionary of language locales to domain list
        required: true
      - key: ckanext.language_domains.secret
        example: 'thisisalegitsecret'
        description: |
          Secret key for JWT encoding.
        required: true
