version: 1
groups:
  - annotation: ckanext-language-domains settings
    options:
      - key: ckanext.language_domains.domain_map
        example: {"en": ["example.com"], "fr": ["exemple.com"]}
        description: |
          Dictionary of language locales to domain list
        required: true
      - key: ckanext.language_domains.root_paths
        example: {"example.com": "/data", "exemple.com": "/data"}
        description: |
          Dictionary of domains and their CKAN root_paths
        required: false
      - key: ckanext.language_domains.secret
        example: 'thisisalegitsecret'
        description: |
          Secret key for JWT encoding.
        required: true
